### ISSUE TITLE
Kneeboard position message issue

### ISSUE THREAD

**Issue by kimiwesker** [whisky-actual/Community-J-10-A#3]
kneeboard position message is not shown properly
Perhaps the font doesn't work or sth. else's not activited
![image](https://user-images.githubusercontent.com/102825638/190836756-e583eb5a-f527-48cb-a78d-4a3da4f0ad1d.png)

**Comment by whisky-actual** [comment]
Hi it's been noted also on the forums, I have an idea what causes it just no time to fix it.
